/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvaliacaoIdRouteImport } from './routes/avaliacao.$id'
import { Route as AtletaNameRouteImport } from './routes/atleta.$name'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacaoIdRoute = AvaliacaoIdRouteImport.update({
  id: '/avaliacao/$id',
  path: '/avaliacao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletaNameRoute = AtletaNameRouteImport.update({
  id: '/atleta/$name',
  path: '/atleta/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atleta/$name': typeof AtletaNameRoute
  '/avaliacao/$id': typeof AvaliacaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atleta/$name': typeof AtletaNameRoute
  '/avaliacao/$id': typeof AvaliacaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atleta/$name': typeof AtletaNameRoute
  '/avaliacao/$id': typeof AvaliacaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/atleta/$name' | '/avaliacao/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/atleta/$name' | '/avaliacao/$id'
  id: '__root__' | '/' | '/login' | '/atleta/$name' | '/avaliacao/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AtletaNameRoute: typeof AtletaNameRoute
  AvaliacaoIdRoute: typeof AvaliacaoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacao/$id': {
      id: '/avaliacao/$id'
      path: '/avaliacao/$id'
      fullPath: '/avaliacao/$id'
      preLoaderRoute: typeof AvaliacaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atleta/$name': {
      id: '/atleta/$name'
      path: '/atleta/$name'
      fullPath: '/atleta/$name'
      preLoaderRoute: typeof AtletaNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AtletaNameRoute: AtletaNameRoute,
  AvaliacaoIdRoute: AvaliacaoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
